name: 'Runner Cleanup'
description: 'Cleans up the runner after a job'
inputs:
  prune-docker:
    description: 'Prune docker: Remove images no longer used by a container.'
    required: false
    default: true
    options:
      - true
      - false
  clean-workspace:
    description: 'Clean the workspace: Wipe the contents.'
    required: false
    default: true
    options:
      - true
      - false
  clear-cache:
    description: 'Clear the cache: Wipe the ~/cache directory.'
    required: false
    default: true
    options:
      - true
      - false
runs:
  using: 'composite'
  steps:
    - name: 'Clean GitHub Workspace'
      if: ${{ inputs.clean-workspace == 'true' }}
      shell: bash
      run: |
        rm -rf "${{ github.workspace }}/{*,.*}"

    - name: 'Clear cache'
      if: ${{ inputs.clear-cache == 'true' }}
      shell: bash
      run: |
        rm -rf "${HOME}/.cache"

    - name: 'Prune Docker'
      if: ${{ inputs.prune-docker == 'true' }}
      shell: bash
      run: |
        docker system prune -f
