---
# This workflow runs after a pull-request has been approved by a reviewer.

name: CI Tests

on:
    pull_request:
        types: [opened, edited, synchronize, ready_for_review]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
    cancel-in-progress: true

jobs:
    pre-commit:
    # runs on github hosted runner
        runs-on: ubuntu-22.04
        if: github.event.pull_request.draft == false
        steps:
            - uses: actions/checkout@v3
