---
name: Docker images build and push

on:
    workflow_dispatch:
jobs:
  # This builds and pushes the docker image.
    build-and-push:
        runs-on: [self-hosted, linux, x64]
        steps:
            # Checkout gem5 so we can use `ADD` for building gem5
            - uses: actions/checkout@v3

            - uses: actions/download-artifact@v3
              with:
                  name: dockerfiles
                  path: .

            - uses: docker/setup-qemu-action@v2
              name: Setup QEMU

            - uses: docker/setup-buildx-action@v2
              name: Set up Docker Buildx

            - uses: docker/login-action@v2
              name: Login to the GitHub Container Registry
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push with bake
              uses: docker/bake-action@v4
              with:
                  files: util/dockerfiles/docker-bake.hcl
                  push: true
