#
name: Docker images build and push

on:
  workflow_dispatch:

env:
  IMAGE_NAME: ubuntu-20.04_all-dependencies
#
jobs:
  # This builds and pushes the docker image.
  push:
    runs-on: [self-hosted, linux, x64, run]
    permissions:
      packages: write
      contents: read
    container: gcr.io/gem5-test/ubuntu-22.04_all-dependencies:latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout the develop branch
        with:
            # Scheduled workflows run on the default branch by default. We
            # therefore need to explicitly checkout the develop branch.
            ref: develop

      - uses: docker/setup-qemu-action@v2
        name: Setup QEMU

      - uses: docker/setup-buildx-action@v2
        name: Set up Docker Buildx

      - uses: docker/login-action@v2
        name: Login to the GitHub Container Registry
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        name: Build and push docker image '$IMAGE_NAME'
        with:
            context: util/dockerfiles/$IMAGE_NAME
            push: true
            platforms: |
                linux/amd64,
                linux/arm64,
                darwin/amd64,
                darwin/arm64
            tags: ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:latest
