---
# This workflow runs all the Weekly GPU Tests.
# For now this file is kept separate as we are still developing and testing
# this workflow. It will eventually be merged with "weekly-tests.yaml"

name: Weekly Tests (GPU)

on:
    pull_request:
        types: [opened, edited, synchronize, ready_for_review]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
    cancel-in-progress: true

jobs:
    build-gem5:
        runs-on: [self-hosted, linux, x64]
        if: github.event.pull_request.draft == false
        container: ghcr.io/gem5/gcn-gpu:latest
        steps:
            - uses: actions/checkout@v3
            - name: Build gem5
              run: scons build/GCN3_X86/gem5.opt -j $(nproc) --ignore-style
            - uses: actions/upload-artifact@v3
              with:
                  name: weekly-test-${{ github.run_number }}-attempt-${{ github.run_attempt }}-gem5-build-gcn3
                  path: build/GCN3_X86/gem5.opt
                  retention-days: 5
            - run: echo "This job's status is ${{ job.status }}."

    HACC-tests:
        runs-on: [self-hosted, linux, x64]
        if: github.event.pull_request.draft == false
        container: ghcr.io/gem5/gcn-gpu:latest
        needs: build-gem5
        timeout-minutes: 120 # 2 hours
        steps:
            - uses: actions/checkout@v3
            - uses: actions/download-artifact@v3
              with:
                  name: weekly-test-${{ github.run_number }}-attempt-${{ github.run_attempt }}-gem5-build-gcn3
                  path: build/GCN3_X86
            - run: chmod u+x build/GCN3_X86/gem5.opt
            - name: make hip directory
              run: mkdir hip
            - name: Compile m5ops and x86
              working-directory: ${{ github.workspace }}/util/m5
              run: |
                  export TERM=xterm-256color
                  scons build/x86/out/m5
            - name: Download tests
              working-directory: ${{ github.workspace }}/hip
              run: wget http://dist.gem5.org/dist/v22-1/test-progs/halo-finder/ForceTreeTest
            - name: Run HACC tests
              working-directory: ${{ github.workspace }}
              run: |
                  build/GCN3_X86/gem5.opt configs/example/apu_se.py -n3 --reg-alloc-policy=dynamic --benchmark-root=hip -c ForceTreeTest --options="0.5 0.1 64 0.1 1 N 12 rcb"
