# This workflow runs all of the very-long tests within main.py

name: Weekly Tests

on:
  # Runs every Sunday from 7AM UTC
  schedule:
    - cron:  '00 7 * * 6'
  # Allows us to manually start workflow for testing
  workflow_dispatch:

jobs:
  build-gem5:
    runs-on: [self-hosted, linux, x64, build]
    container: gcr.io/gem5-test/gcn-gpu:latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Scheduled workflows run on the default branch by default. We
          # therefore need to explicitly checkout the develop branch.
          ref: develop
      - name: Build gem5
        run: scons build/GCN3_X86/gem5.opt -j $(nproc) --ignore-style
      - uses: actions/upload-artifact@v3
        with:
          name: weekly-test-${{ github.run_number }}-attempt-${{ github.run_attempt }}-gem5-build-gcn3
          path: build/GCN3_X86/gem5.opt
          retention-days: 5
      - run: echo "This job's status is ${{ job.status }}."

# These tests run successfully
  LULESH-tests:
    runs-on: [self-hosted, linux, x64, build]
    container: gcr.io/gem5-test/gcn-gpu:latest
    needs: build-gem5
    timeout-minutes: 600 # 10 hours
    steps:
      - uses: actions/checkout@v3
        with:
          # Scheduled workflows run on the default branch by default. We
          # therefore need to explicitly checkout the develop branch.
          ref: develop
      - uses: actions/download-artifact@v3
        with:
          name: weekly-test-${{ github.run_number }}-attempt-${{ github.run_attempt }}-gem5-build-gcn3
          path: build/GCN3_X86
      - run: chmod u+x build/GCN3_X86/gem5.opt
      - name: Compile m5ops and x86
        working-directory: ${{ github.workspace }}/util/m5
        run: |
          export TERM=xterm-256color
          scons build/x86/out/m5
      - name: Build LULESH
        working-directory: ${{ github.workspace }}/lulesh
        # rename lulesh binary in this step so test can find it properly
        run:  |
          wget https://storage.googleapis.com/dist.gem5.org/dist/develop/test-progs/lulesh/lulesh-2023-09-27
          mv lulesh-2023-09-27 lulesh
      - name: Run LULUESH tests
        working-directory: ${{ github.workspace }}
        run: build/GCN3_X86/gem5.opt configs/example/apu_se.py -n3 --mem-size=8GB --reg-alloc-policy=dynamic --benchmark-root="lulesh" -c lulesh
