---
# This workflow runs all of the very-long tests within main.py

name: Weekly Tests

on:
    pull_request:
        types: [opened, edited, synchronize, ready_for_review]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
    cancel-in-progress: true

jobs:
    build-gem5:
        runs-on: [self-hosted, linux, x64]
        if: github.event.pull_request.draft == false
        container: ghcr.io/gem5/ubuntu-22.04_all-dependencies:latest
        outputs:
            build-name: ${{ steps.artifact-name.outputs.name }}
        steps:
            - uses: actions/checkout@v3
            - id: artifact-name
              run: echo "name=$(date +"%Y-%m-%d_%H.%M.%S")-ALL" >> $GITHUB_OUTPUT
            - name: Build gem5
              run: |
                  scons build/ALL/gem5.opt -j $(nproc)
            - uses: actions/upload-artifact@v3
              with:
                  name: ${{ steps.artifact-name.outputs.name }}
                  path: build/ALL/gem5.opt
                  retention-days: 5
            - run: echo "This job's status is ${{ job.status }}."

    dramsys-tests:
        runs-on: [self-hosted, linux, x64]
        if: github.event.pull_request.draft == false
        container: ghcr.io/gem5/ubuntu-22.04_all-dependencies:latest
        timeout-minutes: 4320 # 3 days
        steps:
            - uses: actions/checkout@v3

            - name: Checkout DRAMSys
              working-directory: ${{ github.workspace }}/ext/dramsys
              run: |
                  git clone https://github.com/tukl-msd/DRAMSys DRAMSys
                  cd DRAMSys
                  git checkout -b gem5 09f6dcbb91351e6ee7cadfc7bc8b29d97625db8f
                  git submodule update --init --recursive

      # gem5 is built separately because it depends on the DRAMSys library
            - name: Build gem5
              working-directory: ${{ github.workspace }}
              run: scons build/ALL/gem5.opt -j $(nproc)

            - name: Run DRAMSys Checks
              working-directory: ${{ github.workspace }}
              run: |
                  ./build/ALL/gem5.opt configs/example/gem5_library/dramsys/arm-hello-dramsys.py
                  ./build/ALL/gem5.opt configs/example/gem5_library/dramsys/dramsys-traffic.py
                  ./build/ALL/gem5.opt configs/example/dramsys.py
    weekly-tests:
        # The dummy job is used to indicate whether the weekly tests have
        # passed or not. This can be used as status check for pull requests.
        # I.e., if we want to stop pull requests from being merged if the
        # weekly tests are failing we can add this job as a required status
        # check.
        runs-on: ubuntu-22.04
        needs:
            - build-gem5
            - dramsys-tests
        steps:
            - run: echo "This weekly tests have passed."
